### ISSUE TITLE
LogManager.Configuration.AllTargets is always null

### ISSUE THREAD

**Issue by vijaykumartk** [damienbod/AspNetCoreNlog#3]
Hi, 

```
Am trying to implement the same in my project. None of the methods in the class "ElasticSearchTarget" are getting called in StartUp.cs after calling the method  "loggerFactory.AddNLog();"
```

FYR..

![image](https://cloud.githubusercontent.com/assets/22043055/18577747/73926bda-7c09-11e6-97c2-675ca3463279.png)

hence, LogManager.Configuration.AllTargets is always null and am unable to access the targets.

Am I missing something in the configuration???

**Thanks,
Vijay**

**Comment by damienbod** [comment]
Hi @vijaykumartk 
You need to reference the NLog.Targets.ElasticSearch in your project.json file:
https://github.com/damienbod/AspNetCoreNlog/blob/master/src/AspNetCoreNlog/project.json

And also add the project to your solution.

https://github.com/damienbod/AspNetCoreNlog/tree/master/src/NLog.Targets.ElasticSearch

The nlog config file also needs to be added to the project publish

Greetings Damien

**Comment by vijaykumartk** [comment]
Hi @damienbod  ,

Thanks for the quick response. I have already referenced the NLog.Targets.ElasticSearch in my project.json file and also added the project to my solution.. Still it not working!

FYR..

![image](https://cloud.githubusercontent.com/assets/22043055/18578406/602b560c-7c0d-11e6-925c-63610bba60eb.png)

![image](https://cloud.githubusercontent.com/assets/22043055/18578415/6e3ffce8-7c0d-11e6-81d0-2bfb70977b81.png)

Looking frwrd to see your reply

**Thanks,
Vijay**

**Comment by damienbod** [comment]
Can you check your nlog.config file should be something like this:

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogFile="C:\git\damienbod\AspNetCoreNlog\Logs\internal-nlog.txt">

    <extensions>
        <add assembly="NLog.Targets.ElasticSearch"/>
    </extensions>

  <targets>

    <target name="ElasticSearch" xsi:type="BufferingWrapper" flushTimeout="5000">
      <target xsi:type="ElasticSearch"/>
    </target>

  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="ElasticSearch" />

  </rules>
</nlog>
```

**Comment by vijaykumartk** [comment]
Yes, Its same..

**Comment by damienbod** [comment]
Now I'm getting confused.

Does my example work on your computer?

Greetings Damien

**Comment by vijaykumartk** [comment]
Yes.. The example is working fine. Its not working only when am trying to implement the same in my project.

When I was debugging your example, noticed that the control is going to ElasticSearchTarget.cs immediately after executing the loggerFactory.AddNLog(); method  (in StartUp.cs).  But the same is not happening in mine.

An unable to understand why its happening like that in your example as well!!

Could you please explain?

**Thanks,
Vijay**

**Comment by damienbod** [comment]
Ok, it must be something small.

1) do you have the  "ElasticsearchUrl": "http://localhost:9200" configured in the appsettings?
2) Is one of you paths false?
3) Add 

```
env.ConfigureNLog("nlog.config"); 
```

and remove the other config code (Maybe your app can't find the nlog.config, also add this to the publish options)

```
var configDir = "C:\\git\\damienbod\\AspNetCoreNlog\\Logs";

            if (configDir != string.Empty)
            {
                var logEventInfo = NLog.LogEventInfo.CreateNullEvent();


                foreach (FileTarget target in LogManager.Configuration.AllTargets.Where(t => t is FileTarget))
                {
                    var filename = target.FileName.Render(logEventInfo).Replace("'", "");
                    target.FileName = Path.Combine(configDir, filename);
                }

                LogManager.ReconfigExistingLoggers();
            }
```

**Comment by vijaykumartk** [comment]
@damienbod :+1: Great! Its working now.. :)

Thanks Mate :)

**Comment by damienbod** [comment]
cool
