### ISSUE TITLE
Move to NLog.Web.AspNetCore

### ISSUE THREAD

**Issue by 304NotModified** [damienbod/AspNetCoreNlog#4]
Thanks for the great tutorials!

Since the beta of the NLog.Extensions.Logging, ASP.NET Core users should install [NLog.Web.AspNetCore](https://www.nuget.org/packages/NLog.Web.AspNetCore/). This was needed to support also the non-ASP.NET users.

NLog.Web.AspNetCore has a dependency on NLog.Extensions.Logging, so there is no need to directly install NLog.Extensions.Logging anymore. 

See also [Getting Started with ASP.NET Core (project json)](https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(project.json))

**Comment by 304NotModified** [comment]
Would also fix https://github.com/damienbod/AspNetCoreNlog/issues/2

**Comment by damienbod** [comment]
@304NotModified thanks, I'll do it this week, thanks for the great library.

Greetings Damien

**Comment by damienbod** [comment]
updated

VS2015 project.json version:
https://github.com/damienbod/AspNetCoreNlog/tree/VS2015_project_json

VS2017 msbuild version:
https://github.com/damienbod/AspNetCoreNlog

**Comment by damienbod** [comment]
@304NotModified I try adding ethe extra propeties from the NLog.Web.AspNetCore in the config, but these items are not displayed in the files, databases. Any ideas what could be incorrect?:

Example:

add assembly="NLog.Web.AspNetCore"

url: ${aspnet-request-url}|action: ${aspnet-mvc-action}

**Comment by 304NotModified** [comment]
do you have those 3 settings from step 3? https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(project.json)#3-update-startupcs

**Comment by damienbod** [comment]
No, now it works perfect, thanks

**Comment by damienbod** [comment]
@304NotModified If you want, I could create a pull-request on your repo for getting started with ASP.NET Core csproj. Should I?

**Comment by 304NotModified** [comment]
Well it's a wiki page now, so you could add it ;)

 It's also OK for me to add a link to your github repos if you would prefer that.

**Comment by damienbod** [comment]
ok
