### ISSUE TITLE
Will this sample update to aspnetcore 2.0?

### ISSUE THREAD

**Issue by iJzFan** [damienbod/AspNetCoreNlog#9]
I want to use Nlog in aspnetcore 2.0 & store the logs in SQLServer.But I have no idea to do that.

**Comment by damienbod** [comment]
Yes, as soon as I get time. the last time I checked, I was waiting for NLog at the time. @304NotModified NLog to 2.0 ready?

Greetings Damien

**Comment by 304NotModified** [comment]
partly, not in RTM. But that was also the case for .NET Core 1

See also https://github.com/NLog/NLog.Extensions.Logging/wiki for .NET/ASP.NET Core 2 tutorials

**Comment by 304NotModified** [comment]
FYI, NLog 4.5 has been released (RTM) and has support for ASP.NET 2.0 (and of course ASP.NET 1)

**Comment by damienbod** [comment]
@304NotModified  @iJzFan  Will update today, getting null exceptions for the  NLog.LogManager.Configuration.Variables

**Comment by snakefoot** [comment]
@damienbod It can probably not find the nlog.config. See also:

https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2

Btw. instead of using NLog.LogManager.Configuration.Variables, then you should use `NLog.GlobalDiagnosticsContext.Set("someKey","someValue");` and `${gdc:item=someKey}`. Variables are intended only for use in the nlog.config.

**Comment by damienbod** [comment]
@snakefoot thanks, compiles and runs now, but no logs.

**Comment by snakefoot** [comment]
@damienbod Like I said before, then it can probably not find the nlog.config. Is it configured to be copied into the bin-folder on build ? Have you checked if the nlog.config is in the bin-folder ?

Try adding this line in your Main-method in Program.cs (Taken from the wiki before):

`var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();`

P.S. Make sure to have updated to `NLog.Web.AspNetCore` ver. 4.5.1 and `NLog` ver. 4.5.1

**Comment by damienbod** [comment]
@snakefoot working now, The GlobalDiagnosticsContext does not set the var in the config, but te following works. The order has to be changed.

var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();
LogManager.Configuration.Variables["configDir"] = "C:\\git\\damienbod\\AspNetCoreNlog\\Logs";

thanks!

**Comment by snakefoot** [comment]
Yes when using GDC then you also need to change the nlog.config from `${var:configDir}` to `${gdc:item=configDir}`.

GDC is much more user-friendly when wanting to change global parameters at runtime. The `${var}` might disappear during a configuration-auto-reload. The `${var}` might not work without an additional reload. The `${var}` cannot be configured before having a valid NLog-configuration loaded first.

**Comment by damienbod** [comment]
Having problems updating the ASP.NET Core application

System.AggregateException: 'An error occurred while writing to logger(s). (Could not load type 'NLog.MessageTemplates.MessageTemplateParameter' from assembly 'NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.)'

**Comment by snakefoot** [comment]
> NLog, Version=5.0.0.0

Looks like you are using bad dependencies. Remember to use "NLog.Web.AspNetCore ver. 4.5.1" and "NLog ver. 4.5.1". Also mentioned in the wiki: https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2

**Comment by damienbod** [comment]
No

https://github.com/damienbod/AspNetCoreNlog/blob/dev/src/AspNetCoreNlog/AspNetCoreNlog.csproj

**Comment by snakefoot** [comment]
Yes

https://github.com/damienbod/AspNetCoreNlog/blob/dev/src/NLog.Targets.ElasticSearch/NLog.Targets.ElasticSearch.csproj

Btw. good idea to use nuget-packages instead of copying code.

**Comment by damienbod** [comment]
@snakefoot I removed this from the ASP.NET core project to test, with the same results. Also the is the src for this NuGet package. 

But I never removed the ref ... Sorry!

Thanks for you help.

**Comment by snakefoot** [comment]
So you want me to diagnose issue based on code, that one cannot see. Well guess you have to figure out who has been compiled to use NLog 5.0 and why NLog 5.0 DLL is ending up in your output bin-folder.

**Comment by damienbod** [comment]
@snakefoot No all is tip top. I updated everything, thanks for you help. Will update the blogs, and merge the branch.

Greetings Damien

**Comment by snakefoot** [comment]
Notice that https://www.nuget.org/packages/NLog.Targets.ElasticSearch has been updated to support ElasticSearch ver. 6 (Not sure how your own local copy works out).

**Comment by damienbod** [comment]
Thanks, I will see if I can remove the src code and use the NuGet package, when I created this, the Nuget package did not work with .NET Core

**Comment by damienbod** [comment]
@iJzFan @304NotModified @snakefoot 

Updated
